import React from 'react';
import { View, Text, StyleSheet, Image, ScrollView, TouchableOpacity } from 'react-native';

const ServicoDetalhesScreen = ({ route, navigation }) => {
    const { category } = route.params;

    const services = {
        Manicure: [
            { name: 'Manicure: Spa e Lazer', price: 'R$ 50', stars: 4, image: 'https://i.pinimg.com/736x/52/a6/f7/52a6f7b709d8ab4690ee37594c5b6c18.jpg', address: 'Rua Exemplo, 123', hours: '9:00 - 18:00', description: 'Descrição do serviço de Manicure: Spa e Lazer.' },
            { name: 'Manicure: Beleza Total', price: 'R$ 60', stars: 5, image: 'https://i.pinimg.com/736x/49/9a/17/499a1734c3c8d80a79c98c9ea9c7200b.jpg', address: 'Rua Exemplo, 456', hours: '10:00 - 19:00', description: 'Descrição do serviço de Manicure: Beleza Total.' },
            { name: 'Manicure: Glamour Estética', price: 'R$ 55', stars: 3, image: 'https://i.pinimg.com/736x/3f/79/12/3f791226df5898fcefdef67dd64d9deb.jpg', address: 'Rua Exemplo, 789', hours: '8:00 - 17:00', description: 'Descrição do serviço de Manicure: Glamour Estética.' },
            { name: 'Manicure: Toque de Luxo', price: 'R$ 70', stars: 5, image: 'https://i.pinimg.com/736x/01/49/0d/01490d41976a11b069552c4a735dc331.jpg', address: 'Rua Estilo, 101', hours: '9:00 - 19:00', description: 'Descrição do serviço de Manicure: Toque de Luxo.' },
            { name: 'Manicure: Unhas Naturais', price: 'R$ 40', stars: 4, image: 'https://i.pinimg.com/736x/51/60/77/516077aedb9084ff1b42e3acad10b689.jpg', address: 'Rua Beleza, 202', hours: '10:00 - 18:00', description: 'Descrição do serviço de Manicure: Unhas Naturais.' },
            { name: 'Manicure: Terapia das Unhas', price: 'R$ 65', stars: 5, image: 'https://i.pinimg.com/736x/eb/a7/d6/eba7d605a69fd2b76ff1ae57044f1fc4.jpg', address: 'Rua Cuidado, 303', hours: '9:30 - 18:30', description: 'Descrição do serviço de Manicure: Terapia das Unhas.' },
            { name: 'Manicure: Design Criativo', price: 'R$ 75', stars: 5, image: 'https://i.pinimg.com/736x/73/bd/98/73bd986ddf2351294a9e16bf4e16f6b8.jpg', address: 'Rua Arte, 404', hours: '8:00 - 17:30', description: 'Descrição do serviço de Manicure: Design Criativo.' },
            { name: 'Manicure: Hidratação Profunda', price: 'R$ 45', stars: 4, image: 'https://i.pinimg.com/736x/68/f9/cb/68f9cbed13ea1a07a4234ab4cd1162ad.jpg', address: 'Rua Saúde, 505', hours: '9:00 - 18:00', description: 'Descrição do serviço de Manicure: Hidratação Profunda.' },
            { name: 'Manicure: Express', price: 'R$ 30', stars: 3, image: 'https://i.pinimg.com/736x/80/28/a0/8028a02300c9b6aa2aaece767b607bf0.jpg', address: 'Rua Rápida, 606', hours: '10:00 - 17:00', description: 'Descrição do serviço de Manicure: Express.' },
            { name: 'Manicure: Rê e Nata', price: 'R$ 80', stars: 5, image: 'https://i.pinimg.com/736x/4a/9a/9c/4a9a9c7435bc2ba21546c52c7476e6f1.jpg', address: 'Rua Tendência, 707', hours: '9:00 - 20:00', description: 'Descrição do serviço de Manicure: Rê e Nata.' },
        ],
        Pedicure: [
            { name: 'Pedicure: Beleza Total', price: 'R$ 60', stars: 5, image: 'https://i.pinimg.com/736x/b4/57/7b/b4577b4d9f37195b3d2d53a7e1f7e7bf.jpg', address: 'Rua Exemplo, 456', hours: '10:00 - 19:00', description: 'Descrição do serviço de Pedicure: Beleza Total.' },
            { name: 'Pedicure: Glamour Estética', price: 'R$ 55', stars: 3, image: 'https://i.pinimg.com/736x/06/21/5b/06215b3cf0dacf7ac3c394fd2ccff2a4.jpg', address: 'Rua Exemplo, 789', hours: '8:00 - 17:00', description: 'Descrição do serviço de Pedicure: Glamour Estética.' },
            { name: 'Pedicure: Spa dos Pés', price: 'R$ 70', stars: 5, image: 'https://i.pinimg.com/736x/82/8c/4e/828c4e0ad19331dc59751a030b418b83.jpg', address: 'Rua Relax, 101', hours: '9:00 - 19:00', description: 'Descrição do serviço de Pedicure: Spa dos Pés.' },
            { name: 'Pedicure: Esfoliação Profunda', price: 'R$ 50', stars: 4, image: 'https://i.pinimg.com/736x/98/85/4f/98854f8cf425fb8423ddc9ff90f9d8ff.jpg', address: 'Rua Cuidado, 202', hours: '10:00 - 18:00', description: 'Descrição do serviço de Pedicure: Esfoliação Profunda.' },
            { name: 'Pedicure: Hidratação Intensiva', price: 'R$ 65', stars: 4, image: 'https://i.pinimg.com/736x/60/51/93/6051934ca02c00cbfab1aa00b10e40fe.jpg', address: 'Rua Saúde, 303', hours: '9:30 - 18:30', description: 'Descrição do serviço de Pedicure: Hidratação Intensiva.' },
            { name: 'Pedicure: Cutículas Perfeitas', price: 'R$ 45', stars: 3, image: 'https://i.pinimg.com/736x/78/09/39/78093994d87de15f43bb983c6bc06d7b.jpg', address: 'Rua Beleza, 404', hours: '8:00 - 17:30', description: 'Descrição do serviço de Pedicure: Cutículas Perfeitas.' },
            { name: 'Pedicure: Unhas Decoradas', price: 'R$ 80', stars: 5, image: 'https://i.pinimg.com/736x/65/74/f6/6574f604671c563606b1a4cb4193ec50.jpg', address: 'Rua Arte, 505', hours: '9:00 - 18:00', description: 'Descrição do serviço de Pedicure: Unhas Decoradas.' },
            { name: 'Pedicure: Terapia dos Pés', price: 'R$ 75', stars: 5, image: 'https://i.pinimg.com/736x/de/c2/01/dec20164f60182e029d1138d874a43dc.jpg', address: 'Rua Bem-Estar, 606', hours: '10:00 - 17:00', description: 'Descrição do serviço de Pedicure: Terapia dos Pés.' },
            { name: 'Pedicure: Unhas de Gel', price: 'R$ 90', stars: 5, image: 'https://i.pinimg.com/736x/f7/8d/62/f78d6256af5705ec22730d13f7037a7f.jpg', address: 'Rua Tendência, 707', hours: '9:00 - 20:00', description: 'Descrição do serviço de Pedicure: Unhas de Gel.' },
            { name: 'Pedicure: Detox dos Pés', price: 'R$ 70', stars: 4, image: 'https://i.pinimg.com/736x/11/9c/79/119c79d85456d120dd3dbe45b0be8c00.jpg', address: 'Rua Equilíbrio, 808', hours: '8:00 - 19:00', description: 'Descrição do serviço de Pedicure: Detox dos Pés.' },
        ],
        Decoradas: [
            { name: 'Unhas Decoradas: Beleza Total', price: 'R$ 60', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '10:00 - 19:00', description: 'Descrição do serviço de Unhas Decoradas: Beleza Total.' },
            { name: 'Unhas Decoradas: Glamour Estética', price: 'R$ 55', stars: 3, image: 'link', address: 'Rua Exemplo, 789', hours: '8:00 - 17:00', description: 'Descrição do serviço de Unhas Decoradas: Glamour Estética.' },
            { name: 'Unhas Decoradas: Arte e Estilo', price: 'R$ 70', stars: 5, image: 'link', address: 'Rua Criativa, 101', hours: '9:00 - 19:00', description: 'Descrição do serviço de Unhas Decoradas: Arte e Estilo.' },
            { name: 'Unhas Decoradas: Estilo Sofisticado', price: 'R$ 80', stars: 5, image: 'link', address: 'Rua Elegante, 202', hours: '10:00 - 18:00', description: 'Descrição do serviço de Unhas Decoradas: Estilo Sofisticado.' },
            { name: 'Unhas Decoradas: Fashion Nails', price: 'R$ 75', stars: 5, image: 'link', address: 'Rua Fashion, 303', hours: '9:30 - 18:30', description: 'Descrição do serviço de Unhas Decoradas: Fashion Nails.' },
            { name: 'Unhas Decoradas: Encanto das Unhas', price: 'R$ 65', stars: 4, image: 'link', address: 'Rua Encanto, 404', hours: '8:00 - 17:30', description: 'Descrição do serviço de Unhas Decoradas: Encanto das Unhas.' },
            { name: 'Unhas Decoradas: Pedrarias e Brilho', price: 'R$ 85', stars: 5, image: 'link', address: 'Rua Brilho, 505', hours: '9:00 - 18:00', description: 'Descrição do serviço de Unhas Decoradas: Pedrarias e Brilho.' },
            { name: 'Unhas Decoradas: Criatividade nas Unhas', price: 'R$ 90', stars: 5, image: 'link', address: 'Rua Arte, 606', hours: '10:00 - 17:00', description: 'Descrição do serviço de Unhas Decoradas: Criatividade nas Unhas.' },
            { name: 'Unhas Decoradas: Unhas Artísticas', price: 'R$ 95', stars: 5, image: 'link', address: 'Rua Artística, 707', hours: '9:00 - 20:00', description: 'Descrição do serviço de Unhas Decoradas: Unhas Artísticas.' },
            { name: 'Unhas Decoradas: Unhas 3D', price: 'R$ 100', stars: 5, image: 'link', address: 'Rua 3D, 808', hours: '8:00 - 19:00', description: 'Descrição do serviço de Unhas Decoradas: Unhas 3D.' },
        ],
        Gel: [
            { name: 'Unhas de Gel: Beleza Total', price: 'R$ 90', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '10:00 - 19:00', description: 'Descrição do serviço de Unhas de Gel: Beleza Total.' },
            { name: 'Unhas de Gel: Glamour Estética', price: 'R$ 85', stars: 4, image: 'link', address: 'Rua Exemplo, 789', hours: '8:00 - 17:00', description: 'Descrição do serviço de Unhas de Gel: Glamour Estética.' },
            { name: 'Unhas de Gel: Estilo Sofisticado', price: 'R$ 95', stars: 5, image: 'link', address: 'Rua Elegante, 101', hours: '9:00 - 19:00', description: 'Descrição do serviço de Unhas de Gel: Estilo Sofisticado.' },
            { name: 'Unhas de Gel: Fashion Nails', price: 'R$ 100', stars: 5, image: 'link', address: 'Rua Fashion, 202', hours: '10:00 - 18:00', description: 'Descrição do serviço de Unhas de Gel: Fashion Nails.' },
            { name: 'Unhas de Gel: Unhas de Gel Perfeitas', price: 'R$ 120', stars: 5, image: 'link', address: 'Rua Perfeição, 303', hours: '9:30 - 18:30', description: 'Descrição do serviço de Unhas de Gel: Unhas de Gel Perfeitas.' },
            { name: 'Unhas de Gel: Gel Artístico', price: 'R$ 110', stars: 4, image: 'link', address: 'Rua Arte, 404', hours: '8:00 - 17:30', description: 'Descrição do serviço de Unhas de Gel: Gel Artístico.' },
            { name: 'Unhas de Gel: Gel com Pedrarias', price: 'R$ 130', stars: 5, image: 'link', address: 'Rua Brilho, 505', hours: '9:00 - 18:00', description: 'Descrição do serviço de Unhas de Gel: Gel com Pedrarias.' },
            { name: 'Unhas de Gel: Alongamento de Unhas', price: 'R$ 140', stars: 5, image: 'link', address: 'Rua Alongamento, 606', hours: '10:00 - 17:00', description: 'Descrição do serviço de Unhas de Gel: Alongamento de Unhas.' },
            { name: 'Unhas de Gel: Gel com Decoração', price: 'R$ 125', stars: 5, image: 'link', address: 'Rua Criatividade, 707', hours: '9:00 - 20:00', description: 'Descrição do serviço de Unhas de Gel: Gel com Decoração.' },
            { name: 'Unhas de Gel: Unhas de Gel com Acabamento Matte', price: 'R$ 135', stars: 5, image: 'link', address: 'Rua Matte, 808', hours: '8:00 - 19:00', description: 'Descrição do serviço de Unhas de Gel: Unhas de Gel com Acabamento Matte.' },
        ],
        Extensão: [
            { name: 'Alongamento de Unhas: Beleza Total', price: 'R$ 120', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '10:00 - 19:00', description: 'Descrição do serviço de Alongamento de Unhas: Beleza Total.' },
            { name: 'Alongamento de Unhas: Glamour Estética', price: 'R$ 110', stars: 4, image: 'link', address: 'Rua Exemplo, 789', hours: '8:00 - 17:00', description: 'Descrição do serviço de Alongamento de Unhas: Glamour Estética.' },
            { name: 'Alongamento de Unhas: Estilo Sofisticado', price: 'R$ 130', stars: 5, image: 'link', address: 'Rua Elegante, 101', hours: '9:00 - 19:00', description: 'Descrição do serviço de Alongamento de Unhas: Estilo Sofisticado.' },
            { name: 'Alongamento de Unhas: Fashion Nails', price: 'R$ 140', stars: 5, image: 'link', address: 'Rua Fashion, 202', hours: '10:00 - 18:00', description: 'Descrição do serviço de Alongamento de Unhas: Fashion Nails.' },
            { name: 'Alongamento de Unhas: Unhas Super Longas', price: 'R$ 150', stars: 5, image: 'link', address: 'Rua Longa, 303', hours: '9:30 - 18:30', description: 'Descrição do serviço de Alongamento de Unhas: Unhas Super Longas.' },
            { name: 'Alongamento de Unhas: Alongamento Perfeito', price: 'R$ 160', stars: 5, image: 'link', address: 'Rua Perfeição, 404', hours: '8:00 - 17:30', description: 'Descrição do serviço de Alongamento de Unhas: Alongamento Perfeito.' },
            { name: 'Alongamento de Unhas: Unhas de Gel e Alongamento', price: 'R$ 170', stars: 5, image: 'link', address: 'Rua Gel, 505', hours: '9:00 - 18:00', description: 'Descrição do serviço de Alongamento de Unhas: Unhas de Gel e Alongamento.' },
            { name: 'Alongamento de Unhas: Alongamento com Acrílico', price: 'R$ 180', stars: 5, image: 'link', address: 'Rua Acrílico, 606', hours: '10:00 - 17:00', description: 'Descrição do serviço de Alongamento de Unhas: Alongamento com Acrílico.' },
            { name: 'Alongamento de Unhas: Unhas de Fibra de Vidro', price: 'R$ 190', stars: 5, image: 'link', address: 'Rua Fibra, 707', hours: '9:00 - 20:00', description: 'Descrição do serviço de Alongamento de Unhas: Unhas de Fibra de Vidro.' },
            { name: 'Alongamento de Unhas: Alongamento Natural', price: 'R$ 200', stars: 5, image: 'link', address: 'Rua Natural, 808', hours: '8:00 - 19:00', description: 'Descrição do serviço de Alongamento de Unhas: Alongamento Natural.' },
        ],
        Acrigel: [
            { name: 'Unhas de Acrigel: Beleza Total', price: 'R$ 140', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '10:00 - 19:00', description: 'Descrição do serviço de Unhas de Acrigel: Beleza Total.' },
            { name: 'Unhas de Acrigel: Glamour Estética', price: 'R$ 130', stars: 4, image: 'link', address: 'Rua Exemplo, 789', hours: '8:00 - 17:00', description: 'Descrição do serviço de Unhas de Acrigel: Glamour Estética.' },
            { name: 'Unhas de Acrigel: Estilo Sofisticado', price: 'R$ 150', stars: 5, image: 'link', address: 'Rua Elegante, 101', hours: '9:00 - 19:00', description: 'Descrição do serviço de Unhas de Acrigel: Estilo Sofisticado.' },
            { name: 'Unhas de Acrigel: Fashion Nails', price: 'R$ 160', stars: 5, image: 'link', address: 'Rua Fashion, 202', hours: '10:00 - 18:00', description: 'Descrição do serviço de Unhas de Acrigel: Fashion Nails.' },
            { name: 'Unhas de Acrigel: Unhas Super Longas', price: 'R$ 170', stars: 5, image: 'link', address: 'Rua Longa, 303', hours: '9:30 - 18:30', description: 'Descrição do serviço de Unhas de Acrigel: Unhas Super Longas.' },
            { name: 'Unhas de Acrigel: Acrigel Perfeito', price: 'R$ 180', stars: 5, image: 'link', address: 'Rua Perfeição, 404', hours: '8:00 - 17:30', description: 'Descrição do serviço de Unhas de Acrigel: Acrigel Perfeito.' },
            { name: 'Unhas de Acrigel: Acrigel Artístico', price: 'R$ 190', stars: 5, image: 'link', address: 'Rua Arte, 505', hours: '9:00 - 18:00', description: 'Descrição do serviço de Unhas de Acrigel: Acrigel Artístico.' },
            { name: 'Unhas de Acrigel: Acrigel com Decoração', price: 'R$ 200', stars: 5, image: 'link', address: 'Rua Criatividade, 606', hours: '10:00 - 17:00', description: 'Descrição do serviço de Unhas de Acrigel: Acrigel com Decoração.' },
            { name: 'Unhas de Acrigel: Alongamento com Acrigel', price: 'R$ 210', stars: 5, image: 'link', address: 'Rua Acrílico, 707', hours: '9:00 - 20:00', description: 'Descrição do serviço de Unhas de Acrigel: Alongamento com Acrigel.' },
            { name: 'Unhas de Acrigel: Unhas de Acrigel com Pedrarias', price: 'R$ 220', stars: 5, image: 'link', address: 'Rua Pedrarias, 808', hours: '8:00 - 19:00', description: 'Descrição do serviço de Unhas de Acrigel: Unhas de Acrigel com Pedrarias.' },
        ],
        Corte: [
            { name: 'Corte de Cabelo Feminino: Corte Clássico', price: 'R$ 80', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '10:00 - 19:00', description: 'Descrição do serviço de Corte de Cabelo Feminino: Corte Clássico.' },
            { name: 'Corte de Cabelo Feminino: Corte Moderno', price: 'R$ 90', stars: 4, image: 'link', address: 'Rua Exemplo, 789', hours: '8:00 - 17:00', description: 'Descrição do serviço de Corte de Cabelo Feminino: Corte Moderno.' },
            { name: 'Corte de Cabelo Feminino: Corte Desfiado', price: 'R$ 85', stars: 5, image: 'link', address: 'Rua Elegante, 101', hours: '9:00 - 19:00', description: 'Descrição do serviço de Corte de Cabelo Feminino: Corte Desfiado.' },
            { name: 'Corte de Cabelo Feminino: Corte em Camadas', price: 'R$ 100', stars: 5, image: 'link', address: 'Rua Fashion, 202', hours: '10:00 - 18:00', description: 'Descrição do serviço de Corte de Cabelo Feminino: Corte em Camadas.' },
            { name: 'Corte de Cabelo Feminino: Corte Pixie', price: 'R$ 110', stars: 5, image: 'link', address: 'Rua Fashion, 303', hours: '9:00 - 18:00', description: 'Descrição do serviço de Corte de Cabelo Feminino: Corte Pixie.' },
            { name: 'Corte de Cabelo Feminino: Corte Bob', price: 'R$ 95', stars: 4, image: 'link', address: 'Rua Elegante, 404', hours: '8:30 - 17:30', description: 'Descrição do serviço de Corte de Cabelo Feminino: Corte Bob.' },
            { name: 'Corte de Cabelo Feminino: Corte Longo e Estiloso', price: 'R$ 120', stars: 5, image: 'link', address: 'Rua Longa, 505', hours: '9:00 - 19:00', description: 'Descrição do serviço de Corte de Cabelo Feminino: Corte Longo e Estiloso.' },
            { name: 'Corte de Cabelo Feminino: Corte Curto e Fashion', price: 'R$ 130', stars: 5, image: 'link', address: 'Rua Curta, 606', hours: '10:00 - 18:00', description: 'Descrição do serviço de Corte de Cabelo Feminino: Corte Curto e Fashion.' },
            { name: 'Corte de Cabelo Feminino: Corte Degradê', price: 'R$ 125', stars: 5, image: 'link', address: 'Rua Gradual, 707', hours: '8:00 - 17:00', description: 'Descrição do serviço de Corte de Cabelo Feminino: Corte Degradê.' },
            { name: 'Corte de Cabelo Feminino: Corte com Franjas', price: 'R$ 105', stars: 4, image: 'link', address: 'Rua Franjas, 808', hours: '9:00 - 18:00', description: 'Descrição do serviço de Corte de Cabelo Feminino: Corte com Franjas.' },
        ],
        Pintura: [
            { name: 'Pintura de Cabelo: Mechas Loiras', price: 'R$ 150', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '10:00 - 19:00', description: 'Descrição do serviço de Pintura de Cabelo: Mechas Loiras.' },
            { name: 'Pintura de Cabelo: Pintura Ombré', price: 'R$ 180', stars: 5, image: 'link', address: 'Rua Exemplo, 789', hours: '9:00 - 18:00', description: 'Descrição do serviço de Pintura de Cabelo: Pintura Ombré.' },
            { name: 'Pintura de Cabelo: Mechas Californianas', price: 'R$ 160', stars: 4, image: 'link', address: 'Rua Estilo, 101', hours: '8:00 - 17:00', description: 'Descrição do serviço de Pintura de Cabelo: Mechas Californianas.' },
            { name: 'Pintura de Cabelo: Pintura Full Color', price: 'R$ 170', stars: 5, image: 'link', address: 'Rua Fashion, 202', hours: '10:00 - 18:00', description: 'Descrição do serviço de Pintura de Cabelo: Pintura Full Color.' },
            { name: 'Pintura de Cabelo: Pintura Chocolate', price: 'R$ 150', stars: 5, image: 'link', address: 'Rua Doce, 303', hours: '9:00 - 19:00', description: 'Descrição do serviço de Pintura de Cabelo: Pintura Chocolate.' },
            { name: 'Pintura de Cabelo: Pintura Vermelha', price: 'R$ 160', stars: 5, image: 'link', address: 'Rua Vermelha, 404', hours: '9:30 - 18:30', description: 'Descrição do serviço de Pintura de Cabelo: Pintura Vermelha.' },
            { name: 'Pintura de Cabelo: Pintura Platinada', price: 'R$ 190', stars: 5, image: 'link', address: 'Rua Prata, 505', hours: '8:00 - 17:00', description: 'Descrição do serviço de Pintura de Cabelo: Pintura Platinada.' },
            { name: 'Pintura de Cabelo: Pintura Chocolate Claro', price: 'R$ 170', stars: 5, image: 'link', address: 'Rua Claro, 606', hours: '9:00 - 19:00', description: 'Descrição do serviço de Pintura de Cabelo: Pintura Chocolate Claro.' },
            { name: 'Pintura de Cabelo: Pintura Cobre', price: 'R$ 180', stars: 5, image: 'link', address: 'Rua Cobre, 707', hours: '10:00 - 18:00', description: 'Descrição do serviço de Pintura de Cabelo: Pintura Cobre.' },
            { name: 'Pintura de Cabelo: Pintura Caramelo', price: 'R$ 175', stars: 5, image: 'link', address: 'Rua Caramelo, 808', hours: '9:00 - 17:00', description: 'Descrição do serviço de Pintura de Cabelo: Pintura Caramelo.' },
        ],
        Escova: [
            { name: 'Escova de Cabelo: Escova Modelada', price: 'R$ 70', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '10:00 - 19:00', description: 'Descrição do serviço de Escova de Cabelo: Escova Modelada.' },
            { name: 'Escova de Cabelo: Escova Liso Perfeito', price: 'R$ 80', stars: 4, image: 'link', address: 'Rua Fashion, 789', hours: '9:00 - 18:00', description: 'Descrição do serviço de Escova de Cabelo: Escova Liso Perfeito.' },
            { name: 'Escova de Cabelo: Escova Cachos', price: 'R$ 75', stars: 5, image: 'link', address: 'Rua Estilo, 101', hours: '9:00 - 19:00', description: 'Descrição do serviço de Escova de Cabelo: Escova Cachos.' },
            { name: 'Escova de Cabelo: Escova Progressiva', price: 'R$ 150', stars: 5, image: 'link', address: 'Rua Liso, 202', hours: '9:00 - 18:00', description: 'Descrição do serviço de Escova de Cabelo: Escova Progressiva.' },
            { name: 'Escova de Cabelo: Escova Espelhada', price: 'R$ 100', stars: 5, image: 'link', address: 'Rua Brilho, 303', hours: '8:00 - 17:00', description: 'Descrição do serviço de Escova de Cabelo: Escova Espelhada.' },
            { name: 'Escova de Cabelo: Escova Definitiva', price: 'R$ 120', stars: 5, image: 'link', address: 'Rua Bela, 404', hours: '10:00 - 18:00', description: 'Descrição do serviço de Escova de Cabelo: Escova Definitiva.' },
            { name: 'Escova de Cabelo: Escova Hidratação', price: 'R$ 85', stars: 4, image: 'link', address: 'Rua Hidratante, 505', hours: '9:00 - 18:00', description: 'Descrição do serviço de Escova de Cabelo: Escova Hidratação.' },
            { name: 'Escova de Cabelo: Escova Detox', price: 'R$ 90', stars: 5, image: 'link', address: 'Rua Detox, 606', hours: '8:00 - 17:00', description: 'Descrição do serviço de Escova de Cabelo: Escova Detox.' },
            { name: 'Escova de Cabelo: Escova de Volume', price: 'R$ 95', stars: 5, image: 'link', address: 'Rua Volume, 707', hours: '9:00 - 19:00', description: 'Descrição do serviço de Escova de Cabelo: Escova de Volume.' },
            { name: 'Escova de Cabelo: Escova Relaxante', price: 'R$ 110', stars: 4, image: 'link', address: 'Rua Relaxante, 808', hours: '10:00 - 18:00', description: 'Descrição do serviço de Escova de Cabelo: Escova Relaxante.' },
        ],
        Tratamento: [
            { name: 'Tratamento Capilar: Hidratação Profunda', price: 'R$ 90', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '9:00 - 18:00', description: 'Descrição do serviço de Tratamento Capilar: Hidratação Profunda.' },
            { name: 'Tratamento Capilar: Reconstrução Capilar', price: 'R$ 120', stars: 5, image: 'link', address: 'Rua Estilo, 789', hours: '10:00 - 19:00', description: 'Descrição do serviço de Tratamento Capilar: Reconstrução Capilar.' },
            { name: 'Tratamento Capilar: Cauterização Capilar', price: 'R$ 130', stars: 4, image: 'link', address: 'Rua Beleza, 101', hours: '8:00 - 17:00', description: 'Descrição do serviço de Tratamento Capilar: Cauterização Capilar.' },
            { name: 'Tratamento Capilar: Botox Capilar', price: 'R$ 150', stars: 5, image: 'link', address: 'Rua Liso, 202', hours: '9:00 - 18:00', description: 'Descrição do serviço de Tratamento Capilar: Botox Capilar.' },
            { name: 'Tratamento Capilar: Selagem Térmica', price: 'R$ 160', stars: 5, image: 'link', address: 'Rua Brilho, 303', hours: '9:00 - 19:00', description: 'Descrição do serviço de Tratamento Capilar: Selagem Térmica.' },
            { name: 'Tratamento Capilar: Hidratação de Óleo de Argan', price: 'R$ 110', stars: 4, image: 'link', address: 'Rua Luxo, 404', hours: '10:00 - 18:00', description: 'Descrição do serviço de Tratamento Capilar: Hidratação de Óleo de Argan.' },
            { name: 'Tratamento Capilar: Reconstrução de Fios Danificados', price: 'R$ 140', stars: 5, image: 'link', address: 'Rua Forte, 505', hours: '9:00 - 19:00', description: 'Descrição do serviço de Tratamento Capilar: Reconstrução de Fios Danificados.' },
            { name: 'Tratamento Capilar: Nutrição Capilar', price: 'R$ 100', stars: 5, image: 'link', address: 'Rua Viva, 606', hours: '9:00 - 18:00', description: 'Descrição do serviço de Tratamento Capilar: Nutrição Capilar.' },
            { name: 'Tratamento Capilar: Tratamento Anti-queda', price: 'R$ 130', stars: 5, image: 'link', address: 'Rua Crescimento, 707', hours: '8:00 - 17:00', description: 'Descrição do serviço de Tratamento Capilar: Tratamento Anti-queda.' },
            { name: 'Tratamento Capilar: Reconstrução com Queratina', price: 'R$ 140', stars: 4, image: 'link', address: 'Rua Saúde, 808', hours: '9:00 - 18:00', description: 'Descrição do serviço de Tratamento Capilar: Reconstrução com Queratina.' },
        ],
        Design: [
            { name: 'Design de Sobrancelhas: Desenho com Hena', price: 'R$ 50', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '9:00 - 18:00', description: 'Descrição do serviço de Design de Sobrancelhas: Desenho com Hena.' },
            { name: 'Design de Sobrancelhas: Sobrancelhas Fio a Fio', price: 'R$ 70', stars: 5, image: 'link', address: 'Rua Estilo, 789', hours: '10:00 - 19:00', description: 'Descrição do serviço de Design de Sobrancelhas: Sobrancelhas Fio a Fio.' },
            { name: 'Design de Sobrancelhas: Design Compinado (Sombra e Fio)', price: 'R$ 80', stars: 4, image: 'link', address: 'Rua Beleza, 101', hours: '9:00 - 18:00', description: 'Descrição do serviço de Design de Sobrancelhas: Design Combinado (Sombra e Fio).' },
            { name: 'Design de Sobrancelhas: Hena e Correção', price: 'R$ 60', stars: 5, image: 'link', address: 'Rua Simetria, 202', hours: '9:00 - 17:00', description: 'Descrição do serviço de Design de Sobrancelhas: Hena e Correção.' },
            { name: 'Design de Sobrancelhas: Microblading', price: 'R$ 180', stars: 5, image: 'link', address: 'Rua Beleza, 303', hours: '10:00 - 18:00', description: 'Descrição do serviço de Design de Sobrancelhas: Microblading.' },
            { name: 'Design de Sobrancelhas: Sobrancelhas Perfeitas', price: 'R$ 75', stars: 4, image: 'link', address: 'Rua Harmony, 404', hours: '9:00 - 18:00', description: 'Descrição do serviço de Design de Sobrancelhas: Sobrancelhas Perfeitas.' },
            { name: 'Design de Sobrancelhas: Depilação e Design', price: 'R$ 45', stars: 5, image: 'link', address: 'Rua Delicada, 505', hours: '8:00 - 17:00', description: 'Descrição do serviço de Design de Sobrancelhas: Depilação e Design.' },
            { name: 'Design de Sobrancelhas: Desenho Clássico', price: 'R$ 50', stars: 5, image: 'link', address: 'Rua Clássica, 606', hours: '9:00 - 19:00', description: 'Descrição do serviço de Design de Sobrancelhas: Desenho Clássico.' },
            { name: 'Design de Sobrancelhas: Design Natural', price: 'R$ 60', stars: 4, image: 'link', address: 'Rua Naturale, 707', hours: '9:00 - 18:00', description: 'Descrição do serviço de Design de Sobrancelhas: Design Natural.' },
            { name: 'Design de Sobrancelhas: Laminação de Sobrancelhas', price: 'R$ 90', stars: 5, image: 'link', address: 'Rua Seda, 808', hours: '10:00 - 18:00', description: 'Descrição do serviço de Design de Sobrancelhas: Laminação de Sobrancelhas.' },
        ],
        Henna: [
            { name: 'Henna para Sobrancelhas: Aplicação Completa', price: 'R$ 55', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '9:00 - 18:00', description: 'Descrição do serviço de Henna para Sobrancelhas: Aplicação Completa.' },
            { name: 'Henna para Sobrancelhas: Design e Hidratação', price: 'R$ 70', stars: 5, image: 'link', address: 'Rua Estilo, 789', hours: '10:00 - 19:00', description: 'Descrição do serviço de Henna para Sobrancelhas: Design e Hidratação.' },
            { name: 'Henna para Sobrancelhas: Hena Fio a Fio', price: 'R$ 80', stars: 4, image: 'link', address: 'Rua Beleza, 101', hours: '9:00 - 18:00', description: 'Descrição do serviço de Henna para Sobrancelhas: Hena Fio a Fio.' },
            { name: 'Henna para Sobrancelhas: Hidratação e Modelagem', price: 'R$ 60', stars: 5, image: 'link', address: 'Rua Simetria, 202', hours: '9:00 - 17:00', description: 'Descrição do serviço de Henna para Sobrancelhas: Hidratação e Modelagem.' },
            { name: 'Henna para Sobrancelhas: Aplicação de Henna para Volume', price: 'R$ 65', stars: 5, image: 'link', address: 'Rua Harmonia, 303', hours: '10:00 - 18:00', description: 'Descrição do serviço de Henna para Sobrancelhas: Aplicação de Henna para Volume.' },
            { name: 'Henna para Sobrancelhas: Hidratação Profunda com Henna', price: 'R$ 75', stars: 4, image: 'link', address: 'Rua Beleza, 404', hours: '9:00 - 19:00', description: 'Descrição do serviço de Henna para Sobrancelhas: Hidratação Profunda com Henna.' },
            { name: 'Henna para Sobrancelhas: Design de Sobrancelhas com Henna', price: 'R$ 70', stars: 5, image: 'link', address: 'Rua Elegante, 505', hours: '9:00 - 18:00', description: 'Descrição do serviço de Henna para Sobrancelhas: Design de Sobrancelhas com Henna.' },
            { name: 'Henna para Sobrancelhas: Correção de Sobrancelhas com Henna', price: 'R$ 55', stars: 5, image: 'link', address: 'Rua Delicada, 606', hours: '9:00 - 17:00', description: 'Descrição do serviço de Henna para Sobrancelhas: Correção de Sobrancelhas com Henna.' },
            { name: 'Henna para Sobrancelhas: Hena e Limpeza', price: 'R$ 50', stars: 4, image: 'link', address: 'Rua Limpeza, 707', hours: '9:00 - 19:00', description: 'Descrição do serviço de Henna para Sobrancelhas: Hena e Limpeza.' },
            { name: 'Henna para Sobrancelhas: Design Natural com Henna', price: 'R$ 60', stars: 5, image: 'link', address: 'Rua Natural, 808', hours: '9:00 - 18:00', description: 'Descrição do serviço de Henna para Sobrancelhas: Design Natural com Henna.' },
        ],
        Micropigmentação: [
            { name: 'Micropigmentação de Sobrancelhas: Fio a Fio', price: 'R$ 300', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '9:00 - 18:00', description: 'Descrição do serviço de Micropigmentação de Sobrancelhas: Fio a Fio.' },
            { name: 'Micropigmentação de Sobrancelhas: Sombra', price: 'R$ 350', stars: 5, image: 'link', address: 'Rua Estilo, 789', hours: '10:00 - 19:00', description: 'Descrição do serviço de Micropigmentação de Sobrancelhas: Sombra.' },
            { name: 'Micropigmentação de Sobrancelhas: Design Completo', price: 'R$ 400', stars: 4, image: 'link', address: 'Rua Beleza, 101', hours: '9:00 - 18:00', description: 'Descrição do serviço de Micropigmentação de Sobrancelhas: Design Completo.' },
            { name: 'Micropigmentação de Sobrancelhas: Microblading', price: 'R$ 450', stars: 5, image: 'link', address: 'Rua Simetria, 202', hours: '9:00 - 17:00', description: 'Descrição do serviço de Micropigmentação de Sobrancelhas: Microblading.' },
            { name: 'Micropigmentação de Sobrancelhas: Pêlos Fios Naturais', price: 'R$ 400', stars: 5, image: 'link', address: 'Rua Harmonia, 303', hours: '10:00 - 18:00', description: 'Descrição do serviço de Micropigmentação de Sobrancelhas: Pêlos Fios Naturais.' },
            { name: 'Micropigmentação de Sobrancelhas: Toque de Seda', price: 'R$ 380', stars: 4, image: 'link', address: 'Rua Elegante, 404', hours: '9:00 - 19:00', description: 'Descrição do serviço de Micropigmentação de Sobrancelhas: Toque de Seda.' },
            { name: 'Micropigmentação de Sobrancelhas: Camada Natural', price: 'R$ 350', stars: 5, image: 'link', address: 'Rua Beleza, 505', hours: '9:00 - 18:00', description: 'Descrição do serviço de Micropigmentação de Sobrancelhas: Camada Natural.' },
            { name: 'Micropigmentação de Sobrancelhas: Design e Hidratação', price: 'R$ 390', stars: 5, image: 'link', address: 'Rua Delicada, 606', hours: '9:00 - 17:00', description: 'Descrição do serviço de Micropigmentação de Sobrancelhas: Design e Hidratação.' },
            { name: 'Micropigmentação de Sobrancelhas: Hidratação com Pigmentação', price: 'R$ 370', stars: 4, image: 'link', address: 'Rua Clara, 707', hours: '9:00 - 18:00', description: 'Descrição do serviço de Micropigmentação de Sobrancelhas: Hidratação com Pigmentação.' },
            { name: 'Micropigmentação de Sobrancelhas: Fio a Fio e Sombra', price: 'R$ 450', stars: 5, image: 'link', address: 'Rua Elegante, 808', hours: '9:00 - 19:00', description: 'Descrição do serviço de Micropigmentação de Sobrancelhas: Fio a Fio e Sombra.' },
        ],
        Microblading: [
            { name: 'Microblading: Fio a Fio', price: 'R$ 450', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '9:00 - 18:00', description: 'Descrição do serviço de Microblading: Fio a Fio.' },
            { name: 'Microblading: Design Completo', price: 'R$ 500', stars: 5, image: 'link', address: 'Rua Estilo, 789', hours: '10:00 - 19:00', description: 'Descrição do serviço de Microblading: Design Completo.' },
            { name: 'Microblading: Fios Naturais e Definição', price: 'R$ 480', stars: 4, image: 'link', address: 'Rua Beleza, 101', hours: '9:00 - 18:00', description: 'Descrição do serviço de Microblading: Fios Naturais e Definição.' },
            { name: 'Microblading: Sobrancelhas Fio a Fio', price: 'R$ 470', stars: 5, image: 'link', address: 'Rua Simetria, 202', hours: '9:00 - 17:00', description: 'Descrição do serviço de Microblading: Sobrancelhas Fio a Fio.' },
            { name: 'Microblading: Design e Preenchimento', price: 'R$ 520', stars: 5, image: 'link', address: 'Rua Harmonia, 303', hours: '10:00 - 18:00', description: 'Descrição do serviço de Microblading: Design e Preenchimento.' },
            { name: 'Microblading: Sombra e Fio a Fio', price: 'R$ 530', stars: 5, image: 'link', address: 'Rua Elegante, 404', hours: '9:00 - 19:00', description: 'Descrição do serviço de Microblading: Sombra e Fio a Fio.' },
            { name: 'Microblading: Contorno e Definição', price: 'R$ 490', stars: 4, image: 'link', address: 'Rua Beleza, 505', hours: '9:00 - 18:00', description: 'Descrição do serviço de Microblading: Contorno e Definição.' },
            { name: 'Microblading: Hidratação e Fio a Fio', price: 'R$ 510', stars: 5, image: 'link', address: 'Rua Delicada, 606', hours: '9:00 - 17:00', description: 'Descrição do serviço de Microblading: Hidratação e Fio a Fio.' },
            { name: 'Microblading: Design Natural', price: 'R$ 460', stars: 5, image: 'link', address: 'Rua Clara, 707', hours: '9:00 - 18:00', description: 'Descrição do serviço de Microblading: Design Natural.' },
            { name: 'Microblading: Hidratação com Fio a Fio', price: 'R$ 480', stars: 5, image: 'link', address: 'Rua Elegante, 808', hours: '9:00 - 19:00', description: 'Descrição do serviço de Microblading: Hidratação com Fio a Fio.' },
        ],
        Alongamento: [
            { name: 'Alongamento de Cílios: Fio a Fio', price: 'R$ 150', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '9:00 - 18:00', description: 'Descrição do serviço de Alongamento de Cílios: Fio a Fio.' },
            { name: 'Alongamento de Cílios: Volume Russo', price: 'R$ 200', stars: 5, image: 'link', address: 'Rua Estilo, 789', hours: '10:00 - 19:00', description: 'Descrição do serviço de Alongamento de Cílios: Volume Russo.' },
            { name: 'Alongamento de Cílios: Classic', price: 'R$ 180', stars: 4, image: 'link', address: 'Rua Beleza, 101', hours: '9:00 - 18:00', description: 'Descrição do serviço de Alongamento de Cílios: Classic.' },
            { name: 'Alongamento de Cílios: Mega Volume', price: 'R$ 220', stars: 5, image: 'link', address: 'Rua Simetria, 202', hours: '9:00 - 17:00', description: 'Descrição do serviço de Alongamento de Cílios: Mega Volume.' },
            { name: 'Alongamento de Cílios: Volume Híbrido', price: 'R$ 210', stars: 5, image: 'link', address: 'Rua Harmonia, 303', hours: '10:00 - 18:00', description: 'Descrição do serviço de Alongamento de Cílios: Volume Híbrido.' },
            { name: 'Alongamento de Cílios: Volume 2D', price: 'R$ 190', stars: 4, image: 'link', address: 'Rua Elegante, 404', hours: '9:00 - 19:00', description: 'Descrição do serviço de Alongamento de Cílios: Volume 2D.' },
            { name: 'Alongamento de Cílios: Volume 3D', price: 'R$ 230', stars: 5, image: 'link', address: 'Rua Beleza, 505', hours: '9:00 - 18:00', description: 'Descrição do serviço de Alongamento de Cílios: Volume 3D.' },
            { name: 'Alongamento de Cílios: Lifting de Cílios', price: 'R$ 170', stars: 4, image: 'link', address: 'Rua Delicada, 606', hours: '9:00 - 17:00', description: 'Descrição do serviço de Alongamento de Cílios: Lifting de Cílios.' },
            { name: 'Alongamento de Cílios: Volume 4D', price: 'R$ 240', stars: 5, image: 'link', address: 'Rua Clara, 707', hours: '9:00 - 18:00', description: 'Descrição do serviço de Alongamento de Cílios: Volume 4D.' },
            { name: 'Alongamento de Cílios: Power Volume', price: 'R$ 250', stars: 5, image: 'link', address: 'Rua Elegante, 808', hours: '9:00 - 19:00', description: 'Descrição do serviço de Alongamento de Cílios: Power Volume.' },
        ],
        Lifting: [
            { name: 'Lifting de Cílios: Natural', price: 'R$ 120', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '9:00 - 18:00', description: 'Descrição do serviço de Lifting de Cílios: Natural.' },
            { name: 'Lifting de Cílios: Volume Intenso', price: 'R$ 140', stars: 5, image: 'link', address: 'Rua Estilo, 789', hours: '10:00 - 19:00', description: 'Descrição do serviço de Lifting de Cílios: Volume Intenso.' },
            { name: 'Lifting de Cílios: Power Lift', price: 'R$ 130', stars: 4, image: 'link', address: 'Rua Beleza, 101', hours: '9:00 - 18:00', description: 'Descrição do serviço de Lifting de Cílios: Power Lift.' },
            { name: 'Lifting de Cílios: Efeito Curvado', price: 'R$ 150', stars: 5, image: 'link', address: 'Rua Simetria, 202', hours: '9:00 - 17:00', description: 'Descrição do serviço de Lifting de Cílios: Efeito Curvado.' },
            { name: 'Lifting de Cílios: Volume Natural', price: 'R$ 140', stars: 5, image: 'link', address: 'Rua Harmonia, 303', hours: '10:00 - 18:00', description: 'Descrição do serviço de Lifting de Cílios: Volume Natural.' },
            { name: 'Lifting de Cílios: Curvatura e Definição', price: 'R$ 145', stars: 5, image: 'link', address: 'Rua Elegante, 404', hours: '9:00 - 19:00', description: 'Descrição do serviço de Lifting de Cílios: Curvatura e Definição.' },
            { name: 'Lifting de Cílios: Glamour', price: 'R$ 160', stars: 5, image: 'link', address: 'Rua Beleza, 505', hours: '9:00 - 18:00', description: 'Descrição do serviço de Lifting de Cílios: Glamour.' },
            { name: 'Lifting de Cílios: Lift Profundo', price: 'R$ 170', stars: 5, image: 'link', address: 'Rua Delicada, 606', hours: '9:00 - 17:00', description: 'Descrição do serviço de Lifting de Cílios: Lift Profundo.' },
            { name: 'Lifting de Cílios: Efeito Duradouro', price: 'R$ 155', stars: 5, image: 'link', address: 'Rua Clara, 707', hours: '9:00 - 18:00', description: 'Descrição do serviço de Lifting de Cílios: Efeito Duradouro.' },
            { name: 'Lifting de Cílios: Efeito Fox Eyes', price: 'R$ 180', stars: 5, image: 'link', address: 'Rua Elegante, 808', hours: '9:00 - 19:00', description: 'Descrição do serviço de Lifting de Cílios: Efeito Fox Eyes.' },
        ],
        Coloração: [
            { name: 'Coloração de Cílios: Preto Natural', price: 'R$ 80', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '9:00 - 18:00', description: 'Descrição do serviço de Coloração de Cílios: Preto Natural.' },
            { name: 'Coloração de Cílios: Castanho Claro', price: 'R$ 85', stars: 5, image: 'link', address: 'Rua Estilo, 789', hours: '10:00 - 19:00', description: 'Descrição do serviço de Coloração de Cílios: Castanho Claro.' },
            { name: 'Coloração de Cílios: Preto Intenso', price: 'R$ 90', stars: 4, image: 'link', address: 'Rua Beleza, 101', hours: '9:00 - 18:00', description: 'Descrição do serviço de Coloração de Cílios: Preto Intenso.' },
            { name: 'Coloração de Cílios: Castanho Escuro', price: 'R$ 95', stars: 5, image: 'link', address: 'Rua Simetria, 202', hours: '9:00 - 17:00', description: 'Descrição do serviço de Coloração de Cílios: Castanho Escuro.' },
            { name: 'Coloração de Cílios: Loiro Claro', price: 'R$ 100', stars: 5, image: 'link', address: 'Rua Harmonia, 303', hours: '10:00 - 18:00', description: 'Descrição do serviço de Coloração de Cílios: Loiro Claro.' },
            { name: 'Coloração de Cílios: Loiro Escuro', price: 'R$ 110', stars: 5, image: 'link', address: 'Rua Elegante, 404', hours: '9:00 - 19:00', description: 'Descrição do serviço de Coloração de Cílios: Loiro Escuro.' },
            { name: 'Coloração de Cílios: Azul Profundo', price: 'R$ 120', stars: 4, image: 'link', address: 'Rua Beleza, 505', hours: '9:00 - 18:00', description: 'Descrição do serviço de Coloração de Cílios: Azul Profundo.' },
            { name: 'Coloração de Cílios: Verde Oliva', price: 'R$ 125', stars: 5, image: 'link', address: 'Rua Delicada, 606', hours: '9:00 - 17:00', description: 'Descrição do serviço de Coloração de Cílios: Verde Oliva.' },
            { name: 'Coloração de Cílios: Marrom Dourado', price: 'R$ 115', stars: 5, image: 'link', address: 'Rua Clara, 707', hours: '9:00 - 18:00', description: 'Descrição do serviço de Coloração de Cílios: Marrom Dourado.' },
            { name: 'Coloração de Cílios: Preto Azulado', price: 'R$ 125', stars: 5, image: 'link', address: 'Rua Elegante, 808', hours: '9:00 - 19:00', description: 'Descrição do serviço de Coloração de Cílios: Preto Azulado.' },
        ],
        Postiços: [
            { name: 'Cílios Postiços: Volume', price: 'R$ 50', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '9:00 - 18:00', description: 'Descrição do serviço de Cílios Postiços: Volume.' },
            { name: 'Cílios Postiços: Natural', price: 'R$ 60', stars: 5, image: 'link', address: 'Rua Estilo, 789', hours: '10:00 - 19:00', description: 'Descrição do serviço de Cílios Postiços: Natural.' },
            { name: 'Cílios Postiços: Longos e Elegantes', price: 'R$ 70', stars: 4, image: 'link', address: 'Rua Beleza, 101', hours: '9:00 - 18:00', description: 'Descrição do serviço de Cílios Postiços: Longos e Elegantes.' },
            { name: 'Cílios Postiços: Efeito Gato', price: 'R$ 80', stars: 5, image: 'link', address: 'Rua Simetria, 202', hours: '9:00 - 17:00', description: 'Descrição do serviço de Cílios Postiços: Efeito Gato.' },
            { name: 'Cílios Postiços: Efeito Fios Individuais', price: 'R$ 90', stars: 5, image: 'link', address: 'Rua Harmonia, 303', hours: '10:00 - 18:00', description: 'Descrição do serviço de Cílios Postiços: Efeito Fios Individuais.' },
            { name: 'Cílios Postiços: Mega Volume', price: 'R$ 100', stars: 5, image: 'link', address: 'Rua Elegante, 404', hours: '9:00 - 19:00', description: 'Descrição do serviço de Cílios Postiços: Mega Volume.' },
            { name: 'Cílios Postiços: Curvados e Definidos', price: 'R$ 110', stars: 5, image: 'link', address: 'Rua Beleza, 505', hours: '9:00 - 18:00', description: 'Descrição do serviço de Cílios Postiços: Curvados e Definidos.' },
            { name: 'Cílios Postiços: Volume 3D', price: 'R$ 120', stars: 5, image: 'link', address: 'Rua Delicada, 606', hours: '9:00 - 17:00', description: 'Descrição do serviço de Cílios Postiços: Volume 3D.' },
            { name: 'Cílios Postiços: Efeito Ardente', price: 'R$ 130', stars: 5, image: 'link', address: 'Rua Clara, 707', hours: '9:00 - 18:00', description: 'Descrição do serviço de Cílios Postiços: Efeito Ardente.' },
            { name: 'Cílios Postiços: Alongado e Elegante', price: 'R$ 140', stars: 5, image: 'link', address: 'Rua Elegante, 808', hours: '9:00 - 19:00', description: 'Descrição do serviço de Cílios Postiços: Alongado e Elegante.' },
        ],
        Airbrush: [
            { name: 'Maquiagem Airbrush: Noiva', price: 'R$ 250', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '9:00 - 18:00', description: 'Descrição do serviço de Maquiagem Airbrush: Noiva.' },
            { name: 'Maquiagem Airbrush: Festa', price: 'R$ 200', stars: 5, image: 'link', address: 'Rua Estilo, 789', hours: '10:00 - 19:00', description: 'Descrição do serviço de Maquiagem Airbrush: Festa.' },
            { name: 'Maquiagem Airbrush: Evento Corporativo', price: 'R$ 220', stars: 4, image: 'link', address: 'Rua Beleza, 101', hours: '9:00 - 18:00', description: 'Descrição do serviço de Maquiagem Airbrush: Evento Corporativo.' },
            { name: 'Maquiagem Airbrush: Editorial', price: 'R$ 280', stars: 5, image: 'link', address: 'Rua Simetria, 202', hours: '9:00 - 17:00', description: 'Descrição do serviço de Maquiagem Airbrush: Editorial.' },
            { name: 'Maquiagem Airbrush: Festa de 15 Anos', price: 'R$ 230', stars: 5, image: 'link', address: 'Rua Harmonia, 303', hours: '10:00 - 18:00', description: 'Descrição do serviço de Maquiagem Airbrush: Festa de 15 Anos.' },
            { name: 'Maquiagem Airbrush: Formatura', price: 'R$ 250', stars: 5, image: 'link', address: 'Rua Elegante, 404', hours: '9:00 - 19:00', description: 'Descrição do serviço de Maquiagem Airbrush: Formatura.' },
            { name: 'Maquiagem Airbrush: Maquiagem para TV', price: 'R$ 300', stars: 5, image: 'link', address: 'Rua Beleza, 505', hours: '9:00 - 18:00', description: 'Descrição do serviço de Maquiagem Airbrush: Maquiagem para TV.' },
            { name: 'Maquiagem Airbrush: Maquiagem para Vídeo', price: 'R$ 270', stars: 4, image: 'link', address: 'Rua Delicada, 606', hours: '9:00 - 17:00', description: 'Descrição do serviço de Maquiagem Airbrush: Maquiagem para Vídeo.' },
            { name: 'Maquiagem Airbrush: Super Natural', price: 'R$ 210', stars: 5, image: 'link', address: 'Rua Clara, 707', hours: '9:00 - 18:00', description: 'Descrição do serviço de Maquiagem Airbrush: Super Natural.' },
            { name: 'Maquiagem Airbrush: Noite Glamourosa', price: 'R$ 260', stars: 5, image: 'link', address: 'Rua Elegante, 808', hours: '9:00 - 19:00', description: 'Descrição do serviço de Maquiagem Airbrush: Noite Glamourosa.' },
        ],
        Casamento: [
            { name: 'Maquiagem Casamento: Noiva', price: 'R$ 350', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '9:00 - 18:00', description: 'Descrição do serviço de Maquiagem Casamento: Noiva.' },
            { name: 'Maquiagem Casamento: Maquiagem Completa', price: 'R$ 400', stars: 5, image: 'link', address: 'Rua Estilo, 789', hours: '10:00 - 19:00', description: 'Descrição do serviço de Maquiagem Casamento: Maquiagem Completa.' },
            { name: 'Maquiagem Casamento: Noiva e Damas de Honra', price: 'R$ 600', stars: 5, image: 'link', address: 'Rua Beleza, 101', hours: '9:00 - 18:00', description: 'Descrição do serviço de Maquiagem Casamento: Noiva e Damas de Honra.' },
            { name: 'Maquiagem Casamento: Maquiagem para o Casal', price: 'R$ 550', stars: 5, image: 'link', address: 'Rua Simetria, 202', hours: '9:00 - 17:00', description: 'Descrição do serviço de Maquiagem Casamento: Maquiagem para o Casal.' },
            { name: 'Maquiagem Casamento: Teste de Maquiagem', price: 'R$ 150', stars: 5, image: 'link', address: 'Rua Harmonia, 303', hours: '10:00 - 18:00', description: 'Descrição do serviço de Maquiagem Casamento: Teste de Maquiagem.' },
            { name: 'Maquiagem Casamento: Maquiagem para a Mãe da Noiva', price: 'R$ 250', stars: 4, image: 'link', address: 'Rua Elegante, 404', hours: '9:00 - 19:00', description: 'Descrição do serviço de Maquiagem Casamento: Maquiagem para a Mãe da Noiva.' },
            { name: 'Maquiagem Casamento: Maquiagem para a Mãe do Noivo', price: 'R$ 240', stars: 4, image: 'link', address: 'Rua Beleza, 505', hours: '9:00 - 18:00', description: 'Descrição do serviço de Maquiagem Casamento: Maquiagem para a Mãe do Noivo.' },
            { name: 'Maquiagem Casamento: Maquiagem para Madrinhas', price: 'R$ 280', stars: 5, image: 'link', address: 'Rua Delicada, 606', hours: '9:00 - 17:00', description: 'Descrição do serviço de Maquiagem Casamento: Maquiagem para Madrinhas.' },
            { name: 'Maquiagem Casamento: Maquiagem para Casamento ao Ar Livre', price: 'R$ 350', stars: 5, image: 'link', address: 'Rua Clara, 707', hours: '9:00 - 18:00', description: 'Descrição do serviço de Maquiagem Casamento: Maquiagem para Casamento ao Ar Livre.' },
            { name: 'Maquiagem Casamento: Maquiagem para Mini Wedding', price: 'R$ 400', stars: 5, image: 'link', address: 'Rua Elegante, 808', hours: '9:00 - 19:00', description: 'Descrição do serviço de Maquiagem Casamento: Maquiagem para Mini Wedding.' },
        ],
        Infantil: [
            { name: 'Maquiagem Infantil: Festa de Aniversário', price: 'R$ 120', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '9:00 - 18:00', description: 'Descrição do serviço de Maquiagem Infantil: Festa de Aniversário.' },
            { name: 'Maquiagem Infantil: Maquiagem para Bailinho', price: 'R$ 100', stars: 5, image: 'link', address: 'Rua Estilo, 789', hours: '10:00 - 19:00', description: 'Descrição do serviço de Maquiagem Infantil: Maquiagem para Bailinho.' },
            { name: 'Maquiagem Infantil: Maquiagem para Carnaval', price: 'R$ 90', stars: 5, image: 'link', address: 'Rua Beleza, 101', hours: '9:00 - 17:00', description: 'Descrição do serviço de Maquiagem Infantil: Maquiagem para Carnaval.' },
            { name: 'Maquiagem Infantil: Maquiagem para Festa Temática', price: 'R$ 110', stars: 5, image: 'link', address: 'Rua Simetria, 202', hours: '9:00 - 18:00', description: 'Descrição do serviço de Maquiagem Infantil: Maquiagem para Festa Temática.' },
            { name: 'Maquiagem Infantil: Maquiagem de Princesa', price: 'R$ 130', stars: 5, image: 'link', address: 'Rua Harmonia, 303', hours: '10:00 - 18:00', description: 'Descrição do serviço de Maquiagem Infantil: Maquiagem de Princesa.' },
            { name: 'Maquiagem Infantil: Maquiagem de Super-Herói', price: 'R$ 120', stars: 5, image: 'link', address: 'Rua Elegante, 404', hours: '9:00 - 19:00', description: 'Descrição do serviço de Maquiagem Infantil: Maquiagem de Super-Herói.' },
            { name: 'Maquiagem Infantil: Maquiagem de Bichinho', price: 'R$ 100', stars: 4, image: 'link', address: 'Rua Beleza, 505', hours: '9:00 - 17:00', description: 'Descrição do serviço de Maquiagem Infantil: Maquiagem de Bichinho.' },
            { name: 'Maquiagem Infantil: Maquiagem de Fada', price: 'R$ 140', stars: 5, image: 'link', address: 'Rua Delicada, 606', hours: '9:00 - 18:00', description: 'Descrição do serviço de Maquiagem Infantil: Maquiagem de Fada.' },
            { name: 'Maquiagem Infantil: Maquiagem para Festa de Halloween', price: 'R$ 120', stars: 5, image: 'link', address: 'Rua Clara, 707', hours: '9:00 - 18:00', description: 'Descrição do serviço de Maquiagem Infantil: Maquiagem para Festa de Halloween.' },
            { name: 'Maquiagem Infantil: Maquiagem de Coelhinha', price: 'R$ 110', stars: 5, image: 'link', address: 'Rua Elegante, 808', hours: '9:00 - 19:00', description: 'Descrição do serviço de Maquiagem Infantil: Maquiagem de Coelhinha.' },
        ],
        Artística: [
            { name: 'Maquiagem Artística: Máscara de Carnaval', price: 'R$ 200', stars: 5, image: 'link', address: 'Rua Exemplo, 456', hours: '9:00 - 18:00', description: 'Descrição do serviço de Maquiagem Artística: Máscara de Carnaval.' },
            { name: 'Maquiagem Artística: Maquiagem de Fantasia', price: 'R$ 250', stars: 5, image: 'link', address: 'Rua Estilo, 789', hours: '10:00 - 19:00', description: 'Descrição do serviço de Maquiagem Artística: Maquiagem de Fantasia.' },
            { name: 'Maquiagem Artística: Maquiagem de Esqueleto', price: 'R$ 220', stars: 5, image: 'link', address: 'Rua Beleza, 101', hours: '9:00 - 17:00', description: 'Descrição do serviço de Maquiagem Artística: Maquiagem de Esqueleto.' },
            { name: 'Maquiagem Artística: Maquiagem de Caveira Mexicana', price: 'R$ 230', stars: 5, image: 'link', address: 'Rua Simetria, 202', hours: '9:00 - 18:00', description: 'Descrição do serviço de Maquiagem Artística: Maquiagem de Caveira Mexicana.' },
            { name: 'Maquiagem Artística: Maquiagem de Dragão', price: 'R$ 280', stars: 5, image: 'link', address: 'Rua Harmonia, 303', hours: '10:00 - 18:00', description: 'Descrição do serviço de Maquiagem Artística: Maquiagem de Dragão.' },
            { name: 'Maquiagem Artística: Maquiagem de Tigre', price: 'R$ 240', stars: 5, image: 'link', address: 'Rua Elegante, 404', hours: '9:00 - 19:00', description: 'Descrição do serviço de Maquiagem Artística: Maquiagem de Tigre.' },
            { name: 'Maquiagem Artística: Maquiagem de Pantera', price: 'R$ 250', stars: 5, image: 'link', address: 'Rua Beleza, 505', hours: '9:00 - 17:00', description: 'Descrição do serviço de Maquiagem Artística: Maquiagem de Pantera.' },
            { name: 'Maquiagem Artística: Maquiagem de Mulher-Maravilha', price: 'R$ 260', stars: 5, image: 'link', address: 'Rua Delicada, 606', hours: '9:00 - 18:00', description: 'Descrição do serviço de Maquiagem Artística: Maquiagem de Mulher-Maravilha.' },
            { name: 'Maquiagem Artística: Maquiagem de Alien', price: 'R$ 300', stars: 5, image: 'link', address: 'Rua Clara, 707', hours: '9:00 - 18:00', description: 'Descrição do serviço de Maquiagem Artística: Maquiagem de Alien.' },
            { name: 'Maquiagem Artística: Maquiagem de Zumbi', price: 'R$ 270', stars: 5, image: 'link', address: 'Rua Elegante, 808', hours: '9:00 - 19:00', description: 'Descrição do serviço de Maquiagem Artística: Maquiagem de Zumbi.' },
        ],
        Navalhada: [
            { name: 'Barba: Navalhada Clássica', price: 'R$ 40', stars: 5, image: 'link', address: 'Rua Exemplo, 123', hours: '9:00 - 18:00', description: 'Descrição do serviço de Barba: Navalhada Clássica.' },
            { name: 'Barba: Navalhada de Luxo', price: 'R$ 50', stars: 5, image: 'link', address: 'Rua Estilo, 456', hours: '10:00 - 19:00', description: 'Descrição do serviço de Barba: Navalhada de Luxo.' },
            { name: 'Barba: Navalhada Completa', price: 'R$ 55', stars: 4, image: 'link', address: 'Rua Beleza, 789', hours: '8:00 - 17:00', description: 'Descrição do serviço de Barba: Navalhada Completa.' },
            { name: 'Barba: Navalhada com Massagem', price: 'R$ 60', stars: 5, image: 'link', address: 'Rua Elegante, 101', hours: '9:00 - 18:00', description: 'Descrição do serviço de Barba: Navalhada com Massagem.' },
            { name: 'Barba: Navalhada Tradicional', price: 'R$ 45', stars: 4, image: 'link', address: 'Rua Estilo, 202', hours: '9:00 - 18:00', description: 'Descrição do serviço de Barba: Navalhada Tradicional.' },
            { name: 'Barba: Navalhada Premium', price: 'R$ 70', stars: 5, image: 'link', address: 'Rua Beleza, 303', hours: '10:00 - 19:00', description: 'Descrição do serviço de Barba: Navalhada Premium.' },
            { name: 'Barba: Navalhada com Toalha Quente', price: 'R$ 65', stars: 5, image: 'link', address: 'Rua Simetria, 404', hours: '9:00 - 17:00', description: 'Descrição do serviço de Barba: Navalhada com Toalha Quente.' },
            { name: 'Barba: Navalhada Relaxante', price: 'R$ 50', stars: 5, image: 'link', address: 'Rua Harmonia, 505', hours: '10:00 - 19:00', description: 'Descrição do serviço de Barba: Navalhada Relaxante.' },
            { name: 'Barba: Navalhada com Corte de Cabelo', price: 'R$ 85', stars: 5, image: 'link', address: 'Rua Elegante, 606', hours: '9:00 - 19:00', description: 'Descrição do serviço de Barba: Navalhada com Corte de Cabelo.' },
            { name: 'Barba: Navalhada Deluxe', price: 'R$ 90', stars: 5, image: 'link', address: 'Rua Simetria, 707', hours: '9:00 - 18:00', description: 'Descrição do serviço de Barba: Navalhada Deluxe.' },
        ],
        Alisamento: [
            { name: 'Barba: Alisamento Clássico', price: 'R$ 100', stars: 5, image: 'link', address: 'Rua Exemplo, 123', hours: '9:00 - 18:00', description: 'Descrição do serviço de Barba: Alisamento Clássico.' },
            { name: 'Barba: Alisamento com Escova', price: 'R$ 120', stars: 5, image: 'link', address: 'Rua Estilo, 456', hours: '10:00 - 19:00', description: 'Descrição do serviço de Barba: Alisamento com Escova.' },
            { name: 'Barba: Alisamento Profundo', price: 'R$ 150', stars: 5, image: 'link', address: 'Rua Beleza, 789', hours: '8:00 - 17:00', description: 'Descrição do serviço de Barba: Alisamento Profundo.' },
            { name: 'Barba: Alisamento Premium', price: 'R$ 180', stars: 5, image: 'link', address: 'Rua Elegante, 101', hours: '9:00 - 18:00', description: 'Descrição do serviço de Barba: Alisamento Premium.' },
            { name: 'Barba: Alisamento Completo', price: 'R$ 170', stars: 5, image: 'link', address: 'Rua Estilo, 202', hours: '9:00 - 18:00', description: 'Descrição do serviço de Barba: Alisamento Completo.' },
            { name: 'Barba: Alisamento com Hidratação', price: 'R$ 160', stars: 5, image: 'link', address: 'Rua Beleza, 303', hours: '10:00 - 19:00', description: 'Descrição do serviço de Barba: Alisamento com Hidratação.' },
            { name: 'Barba: Alisamento com Botox Capilar', price: 'R$ 190', stars: 5, image: 'link', address: 'Rua Simetria, 404', hours: '9:00 - 17:00', description: 'Descrição do serviço de Barba: Alisamento com Botox Capilar.' },
            { name: 'Barba: Alisamento Natural', price: 'R$ 140', stars: 5, image: 'link', address: 'Rua Harmonia, 505', hours: '10:00 - 19:00', description: 'Descrição do serviço de Barba: Alisamento Natural.' },
            { name: 'Barba: Alisamento + Cuidados Especiais', price: 'R$ 200', stars: 5, image: 'link', address: 'Rua Elegante, 606', hours: '9:00 - 19:00', description: 'Descrição do serviço de Barba: Alisamento + Cuidados Especiais.' },
            { name: 'Barba: Alisamento Total', price: 'R$ 220', stars: 5, image: 'link', address: 'Rua Simetria, 707', hours: '9:00 - 18:00', description: 'Descrição do serviço de Barba: Alisamento Total.' },
        ],
        Pintura: [
            { name: 'Barba: Pintura Clássica', price: 'R$ 50', stars: 5, image: 'link', address: 'Rua Exemplo, 123', hours: '9:00 - 18:00', description: 'Descrição do serviço de Barba: Pintura Clássica.' },
            { name: 'Barba: Pintura com Sombra', price: 'R$ 55', stars: 5, image: 'link', address: 'Rua Estilo, 456', hours: '10:00 - 19:00', description: 'Descrição do serviço de Barba: Pintura com Sombra.' },
            { name: 'Barba: Pintura Natural', price: 'R$ 60', stars: 4, image: 'link', address: 'Rua Beleza, 789', hours: '8:00 - 17:00', description: 'Descrição do serviço de Barba: Pintura Natural.' },
            { name: 'Barba: Pintura Intensiva', price: 'R$ 70', stars: 5, image: 'link', address: 'Rua Elegante, 101', hours: '9:00 - 18:00', description: 'Descrição do serviço de Barba: Pintura Intensiva.' },
            { name: 'Barba: Pintura Premium', price: 'R$ 80', stars: 5, image: 'link', address: 'Rua Estilo, 202', hours: '9:00 - 18:00', description: 'Descrição do serviço de Barba: Pintura Premium.' },
            { name: 'Barba: Pintura com Hidratação', price: 'R$ 90', stars: 5, image: 'link', address: 'Rua Beleza, 303', hours: '10:00 - 19:00', description: 'Descrição do serviço de Barba: Pintura com Hidratação.' },
            { name: 'Barba: Pintura com Toque de Sombra', price: 'R$ 85', stars: 4, image: 'link', address: 'Rua Simetria, 404', hours: '9:00 - 17:00', description: 'Descrição do serviço de Barba: Pintura com Toque de Sombra.' },
            { name: 'Barba: Pintura Natural com Sombra', price: 'R$ 75', stars: 5, image: 'link', address: 'Rua Harmonia, 505', hours: '10:00 - 19:00', description: 'Descrição do serviço de Barba: Pintura Natural com Sombra.' },
            { name: 'Barba: Pintura e Definição', price: 'R$ 100', stars: 5, image: 'link', address: 'Rua Elegante, 606', hours: '9:00 - 19:00', description: 'Descrição do serviço de Barba: Pintura e Definição.' },
            { name: 'Barba: Pintura Completa', price: 'R$ 120', stars: 5, image: 'link', address: 'Rua Simetria, 707', hours: '9:00 - 18:00', description: 'Descrição do serviço de Barba: Pintura Completa.' },
        ],
        HotTowelShave: [
            { name: 'Barba: Hot Towel Shave Clássico', price: 'R$ 80', stars: 5, image: 'link', address: 'Rua Exemplo, 123', hours: '9:00 - 18:00', description: 'Descrição do serviço de Barba: Hot Towel Shave Clássico.' },
            { name: 'Barba: Hot Towel Shave Premium', price: 'R$ 100', stars: 5, image: 'link', address: 'Rua Estilo, 456', hours: '10:00 - 19:00', description: 'Descrição do serviço de Barba: Hot Towel Shave Premium.' },
            { name: 'Barba: Hot Towel Shave Relaxante', price: 'R$ 90', stars: 4, image: 'link', address: 'Rua Beleza, 789', hours: '8:00 - 17:00', description: 'Descrição do serviço de Barba: Hot Towel Shave Relaxante.' },
            { name: 'Barba: Hot Towel Shave com Massagem', price: 'R$ 110', stars: 5, image: 'link', address: 'Rua Elegante, 101', hours: '9:00 - 18:00', description: 'Descrição do serviço de Barba: Hot Towel Shave com Massagem.' },
            { name: 'Barba: Hot Towel Shave Luxo', price: 'R$ 120', stars: 5, image: 'link', address: 'Rua Estilo, 202', hours: '9:00 - 18:00', description: 'Descrição do serviço de Barba: Hot Towel Shave Luxo.' },
            { name: 'Barba: Hot Towel Shave Completo', price: 'R$ 130', stars: 5, image: 'link', address: 'Rua Beleza, 303', hours: '10:00 - 19:00', description: 'Descrição do serviço de Barba: Hot Towel Shave Completo.' },
            { name: 'Barba: Hot Towel Shave com Aromaterapia', price: 'R$ 140', stars: 5, image: 'link', address: 'Rua Simetria, 404', hours: '9:00 - 17:00', description: 'Descrição do serviço de Barba: Hot Towel Shave com Aromaterapia.' },
            { name: 'Barba: Hot Towel Shave Revitalizante', price: 'R$ 100', stars: 5, image: 'link', address: 'Rua Harmonia, 505', hours: '10:00 - 19:00', description: 'Descrição do serviço de Barba: Hot Towel Shave Revitalizante.' },
            { name: 'Barba: Hot Towel Shave Relax', price: 'R$ 95', stars: 4, image: 'link', address: 'Rua Elegante, 606', hours: '9:00 - 19:00', description: 'Descrição do serviço de Barba: Hot Towel Shave Relax.' },
            { name: 'Barba: Hot Towel Shave VIP', price: 'R$ 150', stars: 5, image: 'link', address: 'Rua Simetria, 707', hours: '9:00 - 18:00', description: 'Descrição do serviço de Barba: Hot Towel Shave VIP.' },
        ],
        Clássico: [
            { name: 'Barba: Hot Towel Shave Clássico', price: 'R$ 80', stars: 5, image: 'link', address: 'Rua Exemplo, 123', hours: '9:00 - 18:00', description: 'O clássico Hot Towel Shave com uma aplicação de toalha quente para amolecer os pelos, seguido de um barbear suave e preciso.' },
            { name: 'Barba: Hot Towel Shave Clássico Deluxe', price: 'R$ 95', stars: 5, image: 'link', address: 'Rua Estilo, 456', hours: '10:00 - 19:00', description: 'Versão deluxe do Hot Towel Shave Clássico com um toque de massagem relaxante.' },
            { name: 'Barba: Hot Towel Shave Clássico e Relax', price: 'R$ 90', stars: 4, image: 'link', address: 'Rua Beleza, 789', hours: '8:00 - 17:00', description: 'Barba com a toalha quente e um toque relaxante para quem busca um cuidado especial.' },
            { name: 'Barba: Hot Towel Shave Clássico com Hidratação', price: 'R$ 100', stars: 5, image: 'link', address: 'Rua Elegante, 101', hours: '9:00 - 18:00', description: 'Barbear clássico com hidratação adicional para a pele após o procedimento.' },
            { name: 'Barba: Hot Towel Shave Clássico e Toque Final', price: 'R$ 85', stars: 5, image: 'link', address: 'Rua Estilo, 202', hours: '9:00 - 18:00', description: 'Finalização clássica com um toque de óleo ou balm para suavizar a pele e o cabelo da barba.' },
            { name: 'Barba: Hot Towel Shave Clássico Aconchego', price: 'R$ 90', stars: 4, image: 'link', address: 'Rua Beleza, 303', hours: '10:00 - 19:00', description: 'Serviço de Hot Towel Shave Clássico com foco em um ambiente aconchegante e relaxante.' },
            { name: 'Barba: Hot Towel Shave Clássico Luxo', price: 'R$ 110', stars: 5, image: 'link', address: 'Rua Simetria, 404', hours: '9:00 - 17:00', description: 'Um serviço de Hot Towel Shave Clássico com um toque de luxo, incluindo massagem e finalização especial.' },
            { name: 'Barba: Hot Towel Shave Clássico com Aromaterapia', price: 'R$ 95', stars: 5, image: 'link', address: 'Rua Harmonia, 505', hours: '10:00 - 19:00', description: 'Experiência Clássica com aromaterapia para um barbear tranquilo e relaxante.' },
            { name: 'Barba: Hot Towel Shave Clássico Refrescante', price: 'R$ 85', stars: 4, image: 'link', address: 'Rua Elegante, 606', hours: '9:00 - 19:00', description: 'Serviço de Hot Towel Shave Clássico com um toque refrescante para um barbear suave e sem irritação.' },
            { name: 'Barba: Hot Towel Shave Clássico Premium', price: 'R$ 120', stars: 5, image: 'link', address: 'Rua Simetria, 707', hours: '9:00 - 18:00', description: 'O Hot Towel Shave Clássico em sua versão premium com mais conforto e cuidado para o cliente.' },
        ],
        Desenhada: [
            { name: 'Barba: Desenhada Clássica', price: 'R$ 40', stars: 5, image: 'link', address: 'Rua Exemplo, 123', hours: '9:00 - 18:00', description: 'Desenhada clássica com precisão, mantendo o contorno da barba sempre bem definido e simétrico.' },
            { name: 'Barba: Desenhada Estilo Moderno', price: 'R$ 50', stars: 5, image: 'link', address: 'Rua Estilo, 456', hours: '10:00 - 19:00', description: 'Barba desenhada com estilo moderno, com um toque arrojado e único.' },
            { name: 'Barba: Desenhada com Design Personalizado', price: 'R$ 60', stars: 4, image: 'link', address: 'Rua Beleza, 789', hours: '8:00 - 17:00', description: 'Design de barba desenhada conforme as preferências e características do cliente.' },
            { name: 'Barba: Desenhada e Hidratação', price: 'R$ 55', stars: 5, image: 'link', address: 'Rua Elegante, 101', hours: '9:00 - 18:00', description: 'Desenhada com hidratação para dar um toque de suavidade à pele e à barba.' },
            { name: 'Barba: Desenhada e Aparada', price: 'R$ 45', stars: 4, image: 'link', address: 'Rua Estilo, 202', hours: '9:00 - 18:00', description: 'Aparar e desenhar a barba com estilo preciso, ideal para quem gosta de uma barba bem cuidada.' },
            { name: 'Barba: Desenhada com Barbeiro Profissional', price: 'R$ 65', stars: 5, image: 'link', address: 'Rua Beleza, 303', hours: '10:00 - 19:00', description: 'Barba desenhada por um barbeiro profissional, com todo o cuidado e precisão.' },
            { name: 'Barba: Desenhada Artística', price: 'R$ 70', stars: 5, image: 'link', address: 'Rua Simetria, 404', hours: '9:00 - 17:00', description: 'Barba desenhada com técnicas artísticas para um design exclusivo e criativo.' },
            { name: 'Barba: Desenhada e Contornada', price: 'R$ 50', stars: 4, image: 'link', address: 'Rua Harmonia, 505', hours: '10:00 - 19:00', description: 'Barba bem desenhada com contornos nítidos, criando um visual moderno e sofisticado.' },
            { name: 'Barba: Desenhada Estilo Vintage', price: 'R$ 55', stars: 5, image: 'link', address: 'Rua Simetria, 606', hours: '9:00 - 19:00', description: 'Desenhada no estilo vintage, com traços finos e simétricos que remetem a épocas passadas.' },
            { name: 'Barba: Desenhada e Finalizada com Balm', price: 'R$ 60', stars: 5, image: 'link', address: 'Rua Elegante, 707', hours: '9:00 - 18:00', description: 'Desenhada com um acabamento suave e finalizada com balm para dar um toque de frescor.' },
        ],
        Aromaterapia: [
            { name: 'Aromaterapia: Relaxante', price: 'R$ 80', stars: 5, image: 'link', address: 'Rua Tranquilidade, 123', hours: '9:00 - 18:00', description: 'Aromaterapia com óleos essenciais para promover relaxamento profundo e alívio do estresse.' },
            { name: 'Aromaterapia: Revitalizante', price: 'R$ 90', stars: 4, image: 'link', address: 'Rua Bem-Estar, 456', hours: '10:00 - 19:00', description: 'Terapia com aromas que revigoram a mente e o corpo, ideal para quem precisa de uma revitalização.' },
            { name: 'Aromaterapia: Calmante', price: 'R$ 75', stars: 5, image: 'link', address: 'Rua Serenidade, 789', hours: '8:00 - 17:00', description: 'Utilização de óleos essenciais calmantes para ajudar no alívio da ansiedade e proporcionar paz interior.' },
            { name: 'Aromaterapia: Detox', price: 'R$ 85', stars: 4, image: 'link', address: 'Rua Purificação, 101', hours: '9:00 - 18:00', description: 'Aromaterapia com óleos que estimulam a desintoxicação do corpo, promovendo um bem-estar geral.' },
            { name: 'Aromaterapia: Equilíbrio Energético', price: 'R$ 95', stars: 5, image: 'link', address: 'Rua Harmonia, 202', hours: '9:00 - 18:00', description: 'Aromas específicos para equilibrar as energias do corpo e da mente, proporcionando sensação de equilíbrio.' },
            { name: 'Aromaterapia: Antidepressiva', price: 'R$ 85', stars: 4, image: 'link', address: 'Rua Paz, 303', hours: '10:00 - 19:00', description: 'Terapia aromática com óleos que ajudam a aliviar sintomas de depressão e promovem sensação de felicidade.' },
            { name: 'Aromaterapia: Estimulante Mental', price: 'R$ 80', stars: 4, image: 'link', address: 'Rua Energia, 404', hours: '9:00 - 18:00', description: 'Aromaterapia com óleos que estimulam a concentração e clareza mental, ideal para aumentar a produtividade.' },
            { name: 'Aromaterapia: Anti-estresse', price: 'R$ 90', stars: 5, image: 'link', address: 'Rua Serenidade, 505', hours: '10:00 - 19:00', description: 'Utilização de óleos aromáticos para aliviar o estresse e proporcionar uma sensação de calma e paz.' },
            { name: 'Aromaterapia: Harmonização de Chakras', price: 'R$ 95', stars: 5, image: 'link', address: 'Rua Equilíbrio, 606', hours: '9:00 - 18:00', description: 'Aromaterapia para equilibrar e harmonizar os chakras, promovendo o bem-estar físico e emocional.' },
            { name: 'Aromaterapia: Rejuvenescedora', price: 'R$ 100', stars: 5, image: 'link', address: 'Rua Vitalidade, 707', hours: '9:00 - 18:00', description: 'Aromaterapia com óleos essenciais para rejuvenescimento da pele e revitalização do corpo.' },
        ],
        HotStone: [
            { name: 'Hot Stone: Terapia Relaxante', price: 'R$ 120', stars: 5, image: 'link', address: 'Rua Tranquilidade, 123', hours: '9:00 - 18:00', description: 'Massagem com pedras quentes para relaxar os músculos e aliviar o estresse.' },
            { name: 'Hot Stone: Equilíbrio Energético', price: 'R$ 130', stars: 4, image: 'link', address: 'Rua Bem-Estar, 456', hours: '10:00 - 19:00', description: 'Terapia com pedras quentes que ajudam a equilibrar a energia do corpo e mente.' },
            { name: 'Hot Stone: Detox Corporal', price: 'R$ 125', stars: 5, image: 'link', address: 'Rua Serenidade, 789', hours: '8:00 - 17:00', description: 'Massagem com pedras quentes que ajudam na desintoxicação do corpo e melhoria da circulação.' },
            { name: 'Hot Stone: Alívio de Tensão', price: 'R$ 110', stars: 4, image: 'link', address: 'Rua Tradição, 101', hours: '9:00 - 18:00', description: 'Terapia com pedras quentes que proporciona alívio de tensões musculares e promove relaxamento.' },
            { name: 'Hot Stone: Revitalização', price: 'R$ 140', stars: 5, image: 'link', address: 'Rua Harmonia, 202', hours: '9:00 - 18:00', description: 'Massagem revitalizante com pedras quentes, ideal para recuperar energia e disposição.' },
            { name: 'Hot Stone: Anti-estresse', price: 'R$ 120', stars: 5, image: 'link', address: 'Rua Paz, 303', hours: '10:00 - 19:00', description: 'Utilização de pedras quentes para aliviar o estresse e proporcionar uma sensação profunda de relaxamento.' },
            { name: 'Hot Stone: Terapia Rejuvenescedora', price: 'R$ 150', stars: 5, image: 'link', address: 'Rua Energia, 404', hours: '9:00 - 18:00', description: 'Massagem com pedras quentes para rejuvenescimento da pele e recuperação do equilíbrio físico e mental.' },
            { name: 'Hot Stone: Circulação e Bem-estar', price: 'R$ 130', stars: 4, image: 'link', address: 'Rua Equilíbrio, 505', hours: '9:00 - 18:00', description: 'Terapia com pedras quentes que melhora a circulação sanguínea e promove uma sensação de bem-estar.' },
            { name: 'Hot Stone: Terapia de Relaxamento Profundo', price: 'R$ 135', stars: 4, image: 'link', address: 'Rua Vitalidade, 606', hours: '9:00 - 18:00', description: 'Massagem profunda com pedras quentes para liberar tensões e proporcionar um relaxamento total.' },
            { name: 'Hot Stone: Alívio de Dores Musculares', price: 'R$ 125', stars: 5, image: 'link', address: 'Rua Bem-Estar, 707', hours: '9:00 - 18:00', description: 'Massagem terapêutica com pedras quentes para aliviar dores musculares e promover relaxamento.' },
        ],

    };
    const selectedServices = services[category] || [];

    return (
        <View style={styles.container}>
            <ScrollView contentContainerStyle={styles.scrollContainer}>
                {selectedServices.length > 0 ? (
                    <View style={styles.servicesGrid}>
                        {selectedServices.map((provider, index) => (
                            <TouchableOpacity
                                key={index}
                                style={styles.providerContainer}
                                onPress={() => navigation.navigate('ServiceDetail', { service: provider })}
                            >
                                <Image source={{ uri: provider.image }} style={styles.providerImage} />
                                <Text style={styles.providerName}>{provider.name}</Text>
                                <Text style={styles.price}>Preço: {provider.price}</Text>
                                <Text style={styles.stars}>Avaliação: {'★'.repeat(provider.stars)}{'☆'.repeat(5 - provider.stars)}</Text>
                            </TouchableOpacity>
                        ))}
                    </View>
                ) : (
                    <Text style={styles.errorText}>Nenhum prestador encontrado para a categoria selecionada.</Text>
                )}
            </ScrollView>
        </View>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
        backgroundColor: '#f5f5f5',
    },
    scrollContainer: {
        paddingBottom: 20,
    },
    servicesGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    providerContainer: {
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 15,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 5,
        shadowOffset: { width: 0, height: 2 },
        width: '48%',
    },
    providerImage: {
        width: '100%',
        height: 150,
        borderRadius: 10,
        marginBottom: 10,
    },
    providerName: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 5,
    },
    price: {
        fontSize: 14,
        color: '#333',
        marginBottom: 5,
    },
    stars: {
        fontSize: 14,
        color: '#f39c12',
    },
    errorText: {
        fontSize: 18,
        color: 'red',
        textAlign: 'center',
        marginTop: 20,
    },
});

export default ServicoDetalhesScreen;
